/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.Restaurante.views;

import com.Restaurante.models.Plato;
import com.Restaurante.models.PlatoInternacional;
import com.Restaurante.models.PlatoNacionaloTipico;
import com.Restaurante.models.Restaurante;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ActualizarPlato extends javax.swing.JDialog {
    
    private Restaurante restaurante;
    private Plato plato;
    private MostrarMenu mostrarMenu;
    
  
    /**
     * Creates new form ActualizarPlato
     */
    public ActualizarPlato(java.awt.Frame parent, boolean modal,VentanaPrincipal ventanaPrincipal, Restaurante restaurante) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try
           {
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/ProyectoFinal/images/icons8-cash-100")).getImage());
        }catch(Exception e)
        {
            
        }
        this.restaurante = restaurante;
        this.plato = plato;
        this.mostrarMenu =mostrarMenu;
        
        this.txtnNombre.setText(this.plato.getNombre());
        this.txtnCosto.setText(Double.toString(this.plato.getCostoFabricacion()));
    }

    private ActualizarPlato(Restaurante restaurante) {
       
        
        setTitle("Actualizar Plato");
        setSize(400, 300);
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtnNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("𝓐𝓬𝓽𝓾𝓪𝓵𝓲𝔃𝓪𝓻 𝓟𝓵𝓪𝓽𝓸");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/actualizar.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 90));

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 230, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        btnVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 90, 40));

        Actualizar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Costo de Fabricacion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txtnCosto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnCostoActionPerformed(evt);
            }
        });
        jPanel2.add(txtnCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 680, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnNombreActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void txtnCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnCostoActionPerformed

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        // TODO add your handling code here:
         try {
        // Crear una nueva instancia de ActualizarPlatoFrame y hacerla visible
        ActualizarPlato actualizarPlatoFrame = new ActualizarPlato (restaurante);
        actualizarPlatoFrame.setVisible(true);
    } catch (Exception e) {
        // Mostrar un mensaje de error en caso de que ocurra una excepción
        JOptionPane.showMessageDialog(this, "Error al intentar actualizar el plato: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       
    }//GEN-LAST:event_ActualizarMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtnCosto;
    private javax.swing.JTextField txtnNombre;
    // End of variables declaration//GEN-END:variables
}
