/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.Restaurante.views;

import com.Restaurante.models.Plato;
import com.Restaurante.models.PlatoInternacional;
import com.Restaurante.models.PlatoNacionaloTipico;
import com.Restaurante.models.Restaurante;
import java.awt.HeadlessException;
import static java.awt.image.ImageObserver.SOMEBITS;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AgregarPlatoInternacional extends javax.swing.JDialog {

    private Restaurante restaurante;
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form AgregarPlatoInternacional
     */
    public AgregarPlatoInternacional(java.awt.Frame parent, boolean modal,Restaurante restaurante,VentanaPrincipal ventana) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("com.Restaurante.imagen.restaurante.png")).getImage());
        }catch(Exception e){
            
        }
        this.restaurante = restaurante;
        this.ventanaPrincipal = ventana;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPaisOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcostoFabricacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("𝓐𝓰𝓻𝓮𝓰𝓪𝓻 𝓟𝓵𝓪𝓽𝓸 𝓘𝓷𝓽𝓮𝓻𝓷𝓪𝓬𝓲𝓸𝓷𝓪𝓵");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, -1));

        jPanel3.setBackground(new java.awt.Color(94, 17, 213));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 90));

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        btnVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 90, 40));

        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Pais Origen");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtPaisOrigen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtPaisOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisOrigenActionPerformed(evt);
            }
        });
        jPanel2.add(txtPaisOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 230, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Costo de Fabricacion");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtcostoFabricacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcostoFabricacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostoFabricacionActionPerformed(evt);
            }
        });
        jPanel2.add(txtcostoFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 680, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String Nombre = txtNombre.getText();
        String PaisOrigen = txtPaisOrigen.getText();
        if(txtNombre.getText().isEmpty()||txtPaisOrigen.getText().isEmpty()||txtcostoFabricacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");
        }else{
            try {
                double costoFabricacion = Double.parseDouble(this.txtcostoFabricacion.getText());
                Plato plato = new PlatoInternacional(PaisOrigen, Nombre, costoFabricacion, costoFabricacion);
                if(this.restaurante.agregarPlato(plato)){
                JOptionPane.showMessageDialog(this, "El plato "+Nombre + " ha sido agregado satisfactoriamente");
                this.dispose();
            }else{
               JOptionPane.showMessageDialog(this, "El plato "+Nombre + "no ha sido agregado satisfactoriamente");
               this.dispose();
            }       
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese un numero en el campo de texto ");
                this.txtcostoFabricacion.setText("");
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtPaisOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisOrigenActionPerformed

    private void txtcostoFabricacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostoFabricacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoFabricacionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaisOrigen;
    private javax.swing.JTextField txtcostoFabricacion;
    // End of variables declaration//GEN-END:variables
}
