/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.Restaurante.views;

import com.Restaurante.models.Plato;
import com.Restaurante.models.Restaurante;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Brayan Diaz
 */
public class MostrarMenu extends javax.swing.JDialog {
    
    
    private ArrayList<Plato> platos;
    private VentanaPrincipal ventanaPrincipal;
    private Restaurante restaurante;
    /**
     * Creates new form MostrarMenu
     */
    public MostrarMenu(java.awt.Frame parent, boolean modal, VentanaPrincipal ventanaPrincipal, Restaurante restaurante) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try{
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/ProyectoFinal/images/icons8-cash-100")).getImage());
        }catch(Exception e)
        {
            
        }
        this.restaurante= restaurante;
        this.ventanaPrincipal = ventanaPrincipal;
        this.platos = restaurante.obtenerTodosPlatos();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        btnActualizarPlato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("𝓜𝓮𝓷𝓾");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/restaurante_1.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 100, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 90));

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Costo", "Ganancia"
            }
        ));
        jScrollPane1.setViewportView(tablaMenu);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 130));

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 100, 30));

        btnVolverMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVolverMenu.setText("Volver");
        btnVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseExited(evt);
            }
        });
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        btnActualizarPlato.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnActualizarPlato.setText("Actualizar");
        btnActualizarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPlatoActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 680, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = this.tablaMenu.getSelectedRow();
        if(fila>=0){
            Plato p = this.platos.get(fila);
            int option = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el plato "+p.getNombre()+" de forma permanente?");
            if(option == 0){
                this.restaurante.eliminarPlato(p.getId());
                this.platos = this.restaurante.obtenerTodosPlatos();
                this.llenarTabla();
                JOptionPane.showMessageDialog(this, "El plato "+p.getNombre()+" fue eliminado de forma exitosa");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione el plato que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseEntered
        
    }//GEN-LAST:event_btnVolverMenuMouseEntered

    private void btnActualizarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPlatoActionPerformed
        int fila = this.tablaMenu.getSelectedRow();
        if(fila>=0){
            Plato p = this.platos.get(fila);
            ActualizarPlato ventanaActualizar = new ActualizarPlato(ventanaPrincipal, true, ventanaPrincipal, restaurante);
            ventanaActualizar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione el plato que desea eliminar");
        }
    }//GEN-LAST:event_btnActualizarPlatoActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnVolverMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMenuMouseExited

    private void btnVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuMouseClicked
        
    private void mouseEntered(JPanel panel){
        panel.setBackground(new Color(255, 131, 7));
    }
    
    private void mouseExited(JPanel panel){
        panel.setBackground(new Color(240,240,240));
    }

    public void llenarTabla(){
        DefaultTableModel modelDefault = new DefaultTableModel(new String[]{"Id","Nombre","Precio", "Costo"}, this.platos.size());
        this.tablaMenu.setModel(modelDefault);
        
        TableModel dataModel = tablaMenu.getModel();
        for (int i = 0; i < this.platos.size(); i++){
            Plato plato = this.platos.get(i);
            
            dataModel.setValueAt(plato.getId(),i,0);
            dataModel.setValueAt(plato.getNombre(),i,1);
            dataModel.setValueAt(plato.getPrecioVenta(),i,2);
            dataModel.setValueAt(plato.getCostoFabricacion(),i,3);           
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPlato;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMenu;
    // End of variables declaration//GEN-END:variables
}
