/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Restaurante.views;

import com.Restaurante.models.Restaurante;
import com.Restaurante.models.Venta;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Brayan Diaz
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Restaurante restaurante;    
    private final ArrayList<Venta> vendidos;
    /**
     * Creates new form VentanaPrincipal2
     */
    public VentanaPrincipal(Restaurante restaurante){
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("com.Restaurante.imagen.restaurante.png")).getImage());
        }catch(Exception e){
            
        }
        this.restaurante = restaurante;
        this.vendidos= restaurante.getVentas();
        this.LblNombreRestaurante.setText(this.restaurante.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LblNombreRestaurante = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregarPlatoInternacional = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAgregarPlatoNacionaloTipico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMostrarMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMostrarVenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarPlato = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnActualizarPlato = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        LblNombreRestaurante.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        LblNombreRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNombreRestaurante.setText("𝓔𝓵 𝓑𝓾𝓮𝓷 𝓢𝓪𝓫𝓸𝓻");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(LblNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LblNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 100));

        jPanel3.setBackground(new java.awt.Color(0, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarPlatoInternacional.setBackground(new java.awt.Color(0, 255, 153));
        btnAgregarPlatoInternacional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoInternacionalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoInternacionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoInternacionalMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/platainternacional.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("𝓘𝓷𝓽𝓮𝓻𝓷𝓪𝓬𝓲𝓸𝓷𝓪𝓵𝓮𝓼");

        javax.swing.GroupLayout btnAgregarPlatoInternacionalLayout = new javax.swing.GroupLayout(btnAgregarPlatoInternacional);
        btnAgregarPlatoInternacional.setLayout(btnAgregarPlatoInternacionalLayout);
        btnAgregarPlatoInternacionalLayout.setHorizontalGroup(
            btnAgregarPlatoInternacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarPlatoInternacionalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(16, 16, 16))
            .addGroup(btnAgregarPlatoInternacionalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarPlatoInternacionalLayout.setVerticalGroup(
            btnAgregarPlatoInternacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPlatoInternacionalLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel3.add(btnAgregarPlatoInternacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnAgregarPlatoNacionaloTipico.setBackground(new java.awt.Color(0, 255, 153));
        btnAgregarPlatoNacionaloTipico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoNacionaloTipicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoNacionaloTipicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoNacionaloTipicoMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/naci.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("𝓝𝓪𝓬𝓲𝓸𝓷𝓪𝓵𝓮𝓼 𝓸 𝓣𝓲𝓹𝓲𝓬𝓸𝓼");

        javax.swing.GroupLayout btnAgregarPlatoNacionaloTipicoLayout = new javax.swing.GroupLayout(btnAgregarPlatoNacionaloTipico);
        btnAgregarPlatoNacionaloTipico.setLayout(btnAgregarPlatoNacionaloTipicoLayout);
        btnAgregarPlatoNacionaloTipicoLayout.setHorizontalGroup(
            btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarPlatoNacionaloTipicoLayout.setVerticalGroup(
            btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(btnAgregarPlatoNacionaloTipico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, 220, 160));

        btnMostrarMenu.setBackground(new java.awt.Color(0, 255, 153));
        btnMostrarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMenuMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/menú.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout btnMostrarMenuLayout = new javax.swing.GroupLayout(btnMostrarMenu);
        btnMostrarMenu.setLayout(btnMostrarMenuLayout);
        btnMostrarMenuLayout.setHorizontalGroup(
            btnMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                .addGroup(btnMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnMostrarMenuLayout.setVerticalGroup(
            btnMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        jPanel3.add(btnMostrarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, 160));

        btnMostrarVenta.setBackground(new java.awt.Color(0, 255, 153));
        btnMostrarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/economia.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("𝓜𝓸𝓼𝓽𝓻𝓪𝓻 𝓥𝓮𝓷𝓽𝓪𝓼");

        javax.swing.GroupLayout btnMostrarVentaLayout = new javax.swing.GroupLayout(btnMostrarVenta);
        btnMostrarVenta.setLayout(btnMostrarVentaLayout);
        btnMostrarVentaLayout.setHorizontalGroup(
            btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                .addGroup(btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11))
                    .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4))
                    .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        btnMostrarVentaLayout.setVerticalGroup(
            btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.add(btnMostrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setText("𝓐𝓰𝓻𝓮𝓰𝓪𝓻 𝓟𝓵𝓪𝓽𝓸𝓼");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("𝓜𝓸𝓼𝓽𝓻𝓪𝓻 𝓜𝓮𝓷𝓾");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        btnBuscarPlato.setBackground(new java.awt.Color(0, 255, 153));
        btnBuscarPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPlatoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarPlatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarPlatoMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/icons8-ensalada-griega-96.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("𝓑𝓾𝓼𝓬𝓪𝓻 𝓟𝓵𝓪𝓽𝓸");

        javax.swing.GroupLayout btnBuscarPlatoLayout = new javax.swing.GroupLayout(btnBuscarPlato);
        btnBuscarPlato.setLayout(btnBuscarPlatoLayout);
        btnBuscarPlatoLayout.setHorizontalGroup(
            btnBuscarPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarPlatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarPlatoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(23, 23, 23))
        );
        btnBuscarPlatoLayout.setVerticalGroup(
            btnBuscarPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarPlatoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanel3.add(btnBuscarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, -1));

        btnActualizarPlato.setBackground(new java.awt.Color(0, 255, 153));
        btnActualizarPlato.setFocusable(false);
        btnActualizarPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPlatoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarPlatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarPlatoMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/icons8-actualizar-100.png"))); // NOI18N
        jLabel12.setVerifyInputWhenFocusTarget(false);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("𝓐𝓬𝓽𝓾𝓪𝓵𝓲𝔃𝓪𝓻");
        jLabel16.setFocusable(false);

        javax.swing.GroupLayout btnActualizarPlatoLayout = new javax.swing.GroupLayout(btnActualizarPlato);
        btnActualizarPlato.setLayout(btnActualizarPlatoLayout);
        btnActualizarPlatoLayout.setHorizontalGroup(
            btnActualizarPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarPlatoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnActualizarPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(btnActualizarPlatoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnActualizarPlatoLayout.setVerticalGroup(
            btnActualizarPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarPlatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jPanel3.add(btnActualizarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 390));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/restaurante_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPlatoNacionaloTipicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoNacionaloTipicoMouseClicked
        AgregarPlatoNacionaloTipico ventanaAgregar = new AgregarPlatoNacionaloTipico(this, true, this.restaurante, this);
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarPlatoNacionaloTipicoMouseClicked

    private void btnAgregarPlatoNacionaloTipicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoNacionaloTipicoMouseEntered
       this.mouseEntered(btnAgregarPlatoNacionaloTipico);
    }//GEN-LAST:event_btnAgregarPlatoNacionaloTipicoMouseEntered

    private void btnAgregarPlatoNacionaloTipicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoNacionaloTipicoMouseExited
        this.mouseEcited(btnAgregarPlatoNacionaloTipico);
    }//GEN-LAST:event_btnAgregarPlatoNacionaloTipicoMouseExited

    private void btnAgregarPlatoInternacionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoInternacionalMouseClicked
        AgregarPlatoInternacional ventanaAgregar = new AgregarPlatoInternacional(this, true, this.restaurante, this);
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarPlatoInternacionalMouseClicked

    private void btnAgregarPlatoInternacionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoInternacionalMouseEntered
       this.mouseEntered(btnAgregarPlatoInternacional);
    }//GEN-LAST:event_btnAgregarPlatoInternacionalMouseEntered

    private void btnAgregarPlatoInternacionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoInternacionalMouseExited
       this.mouseEcited(btnAgregarPlatoInternacional);
    }//GEN-LAST:event_btnAgregarPlatoInternacionalMouseExited

    private void btnMostrarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMenuMouseClicked
        MostrarMenu ventanaMenu = new MostrarMenu(this, true, this, this.restaurante);
        ventanaMenu.setVisible(true);
    }//GEN-LAST:event_btnMostrarMenuMouseClicked

    private void btnMostrarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMenuMouseEntered
       this.mouseEntered(btnMostrarMenu);
    }//GEN-LAST:event_btnMostrarMenuMouseEntered

    private void btnMostrarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMenuMouseExited
        this.mouseEcited(btnMostrarMenu);
    }//GEN-LAST:event_btnMostrarMenuMouseExited

    private void btnMostrarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseClicked
        MostraVenta ventanaVenta = new MostraVenta(this, true, this.restaurante, this);
        ventanaVenta.setVisible(true);
    }//GEN-LAST:event_btnMostrarVentaMouseClicked

    private void btnMostrarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseEntered
        this.mouseEntered(btnMostrarVenta);
    }//GEN-LAST:event_btnMostrarVentaMouseEntered

    private void btnMostrarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseExited
       this.mouseEcited(btnMostrarVenta);
    }//GEN-LAST:event_btnMostrarVentaMouseExited

    private void btnBuscarPlatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPlatoMouseEntered
       this.mouseEntered(btnBuscarPlato);
    }//GEN-LAST:event_btnBuscarPlatoMouseEntered

    private void btnBuscarPlatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPlatoMouseExited
        this.mouseEcited(btnBuscarPlato);
    }//GEN-LAST:event_btnBuscarPlatoMouseExited

    private void btnBuscarPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPlatoMouseClicked
        BuscarPlato ventanaBuscar = new BuscarPlato(this, true, this.restaurante, this);
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_btnBuscarPlatoMouseClicked

    private void btnActualizarPlatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPlatoMouseEntered
        this.mouseEntered(btnActualizarPlato);
    }//GEN-LAST:event_btnActualizarPlatoMouseEntered

    private void btnActualizarPlatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPlatoMouseExited
        this.mouseEcited(btnActualizarPlato);
    }//GEN-LAST:event_btnActualizarPlatoMouseExited

    private void btnActualizarPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPlatoMouseClicked
        ActualizarPlato ventanaActualizar = new ActualizarPlato(this, true, this, this.restaurante);
        ventanaActualizar.setVisible(true);
    }//GEN-LAST:event_btnActualizarPlatoMouseClicked

    private void mouseEntered(JPanel panel){
        panel.setBackground(new Color(0,255,153));
    }
    private void mouseEcited(JPanel panel){
        panel.setBackground(new Color(0,255,153));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblNombreRestaurante;
    private javax.swing.JPanel btnActualizarPlato;
    private javax.swing.JPanel btnAgregarPlatoInternacional;
    private javax.swing.JPanel btnAgregarPlatoNacionaloTipico;
    private javax.swing.JPanel btnBuscarPlato;
    private javax.swing.JPanel btnMostrarMenu;
    private javax.swing.JPanel btnMostrarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
